import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Clock from "../components/Clock";
import Settings from "../components/Settings";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [color, setColor] = useState("red");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Settings setColor={setColor} color={color} />
        <Clock color={color} />
      </main>
    </div>
  );
}
